version: '3.8'
services:
  db:
    container_name: db_personal_wb
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_personal_wb
    image: dpage/pgadmin4
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5055:80"